GET http://localhost:3000/ HTTP/1.1

###

GET http://localhost:3000/api/blogposts/ HTTP/1.1

###

GET http://localhost:3000/api/blogposts/2 HTTP/1.1

### GET all users

GET http://localhost:3000/api/users/ HTTP/1.1

### GET user by ID

GET http://localhost:3000/api/users/7 HTTP/1.1


### GET all users

GET http://localhost:3000/api/todos/ HTTP/1.1

### GET user by ID

GET http://localhost:3000/api/todos/1 HTTP/1.1

###

POST http://localhost:3000/api/blogposts HTTP/1.1
Content-Type: application/json

{
    "title": "title of blog post! Let's go Moe! ",
    "body": "Here is a paragraph about nothing. SeinField would be proud.",
    "userId": 1
}



###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "David Beckham ",
    "username": "DavidRobertBeckham",
    "email": "davidbeckham@gmail.com"
}

###

POST http://localhost:3000/api/todos HTTP/1.1
Content-Type: application/json

{
    "userId": "77",
    "id": "5555",
    "title": "Bend it like beckham",
    "completed": "true"
}